/* 🤖 this file was generated by svg-to-ts */
export const svgIconChevronDown: {
    name: 'icon_chevron_down';
    data: string;
} = {
    name: 'icon_chevron_down',
    data: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"><path fill="currentColor" d="M9.193 14.237a1.144 1.144 0 0 0 1.617 0l6.855-6.855a1.144 1.144 0 0 0-1.617-1.618L10 11.812 3.952 5.768a1.144 1.144 0 0 0-1.617 1.617L9.19 14.24z"/></svg>`
};
export const svgIconChevronLeft: {
    name: 'icon_chevron_left';
    data: string;
} = {
    name: 'icon_chevron_left',
    data: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"><path fill="currentColor" d="M4.764 9.193a1.144 1.144 0 0 0 0 1.617l6.855 6.855a1.144 1.144 0 0 0 1.618-1.617L7.189 10l6.044-6.048a1.144 1.144 0 0 0-1.617-1.617L4.76 9.19z"/></svg>`
};
export type svgIcon = 'icon_chevron_down' | 'icon_chevron_left';
export interface SvgIcon {
    name: svgIcon;
    data: string;
}
export type SvgIconNameSubset<T extends Readonly<SvgIcon[]>> = T[number]['name'];
export const completeIconSet = [svgIconChevronDown, svgIconChevronLeft];
